CREATE USER IF NOT EXISTS 'connectuser'@'%' IDENTIFIED WITH mysql_native_password BY 'connnect';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'connectuser'@'%';
FLUSH PRIVILEGES;